# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test_proto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "test_proto.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10test_proto.proto\x12\ntest_proto"\xaa\x02\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12"\n\x06status\x18\x05 \x01(\x0e\x32\x12.test_proto.Status\x12\r\n\x05roles\x18\x06 \x03(\t\x12,\n\x06scores\x18\x07 \x03(\x0b\x32\x1c.test_proto.User.ScoresEntry\x12$\n\x07\x61\x64\x64ress\x18\x08 \x01(\x0b\x32\x13.test_proto.Address\x12\x14\n\navatar_url\x18\t \x01(\tH\x00\x12\x16\n\x0c\x61vatar_bytes\x18\n \x01(\x0cH\x00\x1a-\n\x0bScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x42\x08\n\x06\x61vatar"R\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\x0b\n\x03lat\x18\x04 \x01(\x02\x12\x0b\n\x03lng\x18\x05 \x01(\x02"q\n\rRecursiveNode\x12\r\n\x05value\x18\x01 \x01(\x05\x12\'\n\x04left\x18\x02 \x01(\x0b\x32\x19.test_proto.RecursiveNode\x12(\n\x05right\x18\x03 \x01(\x0b\x32\x19.test_proto.RecursiveNode*/\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0c\n\x08INACTIVE\x10\x02\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "test_proto_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_USER_SCORESENTRY"]._loaded_options = None
    _globals["_USER_SCORESENTRY"]._serialized_options = b"8\001"
    _globals["_STATUS"]._serialized_start = 532
    _globals["_STATUS"]._serialized_end = 579
    _globals["_USER"]._serialized_start = 33
    _globals["_USER"]._serialized_end = 331
    _globals["_USER_SCORESENTRY"]._serialized_start = 276
    _globals["_USER_SCORESENTRY"]._serialized_end = 321
    _globals["_ADDRESS"]._serialized_start = 333
    _globals["_ADDRESS"]._serialized_end = 415
    _globals["_RECURSIVENODE"]._serialized_start = 417
    _globals["_RECURSIVENODE"]._serialized_end = 530
# @@protoc_insertion_point(module_scope)
